# Generated by Django 5.2.8 on 2025-11-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]